image: node:10.15.3

pipelines:
  branches:
    master:
      - step:
          name: Build production
          caches:
            - node
          script:
            - npm install
            - npm run build
    develop:
      - step:
          name: Build staging
          caches:
            - node
          script:
            - npm install
            - npm run build
  pull-requests:
    feature/*:
      - step:
          name: Feature test
          caches:
            - node
          script:
            - npm install
            - npm test